-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jul 29, 2016 at 03:15 PM
-- Server version: 5.6.26
-- PHP Version: 5.6.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE IF NOT EXISTS `category` (
  `categoryID` int(2) NOT NULL,
  `name` varchar(30) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`categoryID`, `name`) VALUES
(1, 'Mughlai cuisine'),
(2, 'Indo Chinese'),
(3, 'Bread'),
(4, 'Beverages'),
(5, 'Desert');

-- --------------------------------------------------------

--
-- Table structure for table `stock`
--

CREATE TABLE IF NOT EXISTS `stock` (
  `recipeID` int(2) NOT NULL,
  `name` varchar(100) NOT NULL,
  `categoryID` int(2) NOT NULL,
  `thumbnail` varchar(50) NOT NULL,
  `ingriedent` varchar(1000) NOT NULL,
  `method` varchar(3000) NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `stock`
--

INSERT INTO `stock` (`recipeID`, `name`, `categoryID`, `thumbnail`, `ingriedent`, `method`) VALUES
(2, 'Gulab Jamun', 5, 'gulab-jamun.jpg', '*(measuring cup used, 1 cup = 250 ml)<br>\r\nI) 1 cup milk powder<br>\r\n2) 1/4 cup all purpose flour or                    \r\n   maida<br>\r\n3) 1 tsp oil or 1/2 tsp ghee<br>\r\n4) a pinch of salt (optional)<br>\r\n5) a pinch of baking soda<br>\r\n6) 1 to 2 tbsp yogurt<br>\r\n7) a few blanched pistachio or almond    slices for garnishing<br>\r\n8) for the sugar syrup:<br>\r\n9) 2 cups water<br>\r\n10) 1.5 cups sugar<br>\r\n11) 3-4 green cardamoms, husked & \r\n\r\n    crushed or powdered<br>\r\n12) a pinch of saffron/kesar (optional)<br>\r\n13) 1 tsp rose water (optional)<br>', '1) mix water, sugar, cardamom and    \r\n   saffron.<br>\r\n2) keep this sugar solution on fire and \r\n   cook till you get a syrup \r\n   consistency.<br>\r\n3) there should be no thread formation \r\n   in the sugar solution.<br>\r\n4) stir in the rose water and keep \r\n   aside.<br>\r\n\r\n  preparing the jamuns:<br>\r\n5) first mix the milk powder, all \r\n   purpose flour, soda in a bowl.<br>\r\n6) add oil or ghee and just 1 tbsp of  \r\n   yogurt.<br>\r\n7) mix and keep on adding little of the \r\n   yogurt to get a soft sticky mixture.\r\n   <br>\r\n8) the dough should not be crumbly or \r\n   dry. if it is then add some yogurt.\r\n  <br>\r\n9) make smooth small balls from the \r\n   dough.<br>\r\n10) heat the oil and the reduce the \r\n    flame to low.<br>\r\n11) add the balls and fry them stirring \r\n    often to get even color.<br>\r\n12) when they become golden, remove from    \r\n   a slotted spoon and add them to the \r\n  sugar syrup.<br>\r\n13) let them soak in the sugar syrup for \r\n  atleast 1-2 hours.<br>\r\n14) gulab jamuns can be served warm or \r\n  cold. if they are at room temperature, \r\n  then warm in the microwave and serve \r\n   gulab jamun topped with sugar syrup.<br>'),
(3, 'Ras Malai', 5, 'ras.jpeg', '\r\n1) 12 to 15 rasgullas, homemade or store \r\n  brought ones<br>\r\n2) 1 litre whole full fat cow milk, 4 \r\n   cups<br>\r\n3) 4 to 5 tbsp sugar or add as \r\n\r\n   required<br>\r\n4) 10 to 12 tbsp almonds, blanched<br>\r\n5) 10 to 12 unsalted pistachios, \r\n  blanched<br>\r\n6) 1/2 cup water for blanching the \r\n   almonds & pistachios<br>\r\n7) 1/2 tsp cardamom powder<br>\r\n8) 1 to 2 tsp rose water or kewra \r\n  water<br>\r\n9) 8 to 10 saffron strands<br>\r\n10) a few saffron strands for \r\n   garnish<br>\r\n', '1) boil 1/2 cup water. then add almonds \r\n  & pistachios. cover and keep aside for \r\n  30 to 40 minutes.<br>\r\n2) after 30 minutes, peel the almonds, \r\n   pistachios and slice them. keep \r\n   aside.<br>\r\n3) when the almonds are blanching, take \r\n   1 litre of milk in a thick bottomed \r\n   pan or kadai.<br>\r\n4) bring the milk to a boil on medium \r\n   flame.<br>\r\n5) whilst the milk is coming to a boil, \r\n   take 2 tbsp milk from the pan in a \r\n   small bowl. let this milk<br>\r\n6) become warm and then add crushed \r\n   saffron strands. stir and keep aside.\r\n  <br>\r\n7) once the milk has come to a boil, \r\n  then lower the flame and simmer the \r\n   milk.<br>\r\n8) collect the floating cream on the \r\n   sides. continue to cook this way till \r\n   the milk is reduced to half.<br>\r\n9) keep on collecting the cream which \r\n   floats on the top and move it to the \r\n   sides. also keep on stirring the milk \r\n   at intervals so that the milk does \r\n   not get scorched at the bottom.<br>\r\n10) add sugar and stir well so that the \r\n   sugar dissolves.<br>\r\n11) then add cardamom powder.<br>\r\n12)add the sliced almonds & pistachios. \r\n   reserve a few almonds & pistachios \r\n   for garnishing.<br>\r\n13) also add the saffron dissolved milk.\r\n  <br>\r\n14) stir again. keep simmering the \r\n   reduced milk at a low flame.<br>\r\n15) mean while take each rasgulla and \r\n   with a spatula apply pressure, so the \r\n   excess sugar syrup is removed from \r\n   it.<br>\r\n16) you can also press the rasgulla in \r\n   your palms. <br>\r\n17) be gentle and don''t apply too much \r\n   of pressure. <br>\r\n18) as then the rasgullas will break.\r\n  <br>\r\n19) do this with all the rasgullas.<br>\r\n20) now place the rasgullas in the \r\n  simmering milk and simmer for 3 to 4 \r\n   minutes.<br>\r\n21) switch off the flame and then add 1 \r\n   tsp rose water or kewra water \r\n  (pandanus extract).<br>\r\n22) stir gently. cover and let the \r\n   rasmalai come to a room temperature.\r\n  <br>\r\n23) then chill and serve garnished with \r\n   some sliced almonds or pistachios and \r\n   saffron strands.<br>\r\n24) serve rasmalai.<br>\r\n\r\n  <br>\r\n'),
(1, 'Kulfi', 5, 'kulfi.jpg', '1) 3 cups full fat whole milk - 750 ml<br>\r\n2) 75 to 80 gms mawa/khoya/evaporated milk, about 3.5 to 4 tbsp<br>\r\n3) 2 tbsp to 3 tbsp organic unrefined cane sugar or regular sugar, adjust as required - i added 3 tbsp of unrefined cane sugar<br>\r\n4) 1.5 tbsp rice flour or 1 tbsp corn flour<br>\r\n5) 3 tbsp milk to dissolve the rice flour or corn flour<br>\r\n6) 20 shelled unsalted pistachios<br>\r\n7) 20 almonds<br>\r\n8) 4 cardamoms, powdered in a mortar-pestle<br>\r\n9) 1 tsp kewra water (pandanus or screw pine) or rose water or a drop of kewra essence or rose essence<br>\r\n10) 2 pinch of saffron, crushed<br>\r\n', '1) in a wide pan or kadai, heat milk on a sim or low flame for at least about 18 to 20 mins.<br>\r\n2) the milk will reduce and thicken in this period of time.<br>\r\n3) grate the khoya or crumble it very well. keep aside.<br>\r\n4) powder the pistachios and almonds to a semi fine consistency in a dry grinder or in a mortar-pestle.<br>\r\n5) keep both of them aside.<br>\r\n6) crush the cardamom pods in a mortar-pestle and powder finely, discard the husks.<br>\r\n7) dissolve the rice flour or corn starch in 3 tbsp milk, mix very well, keep aside.<br>\r\n8) after 18 to 20 mins, add the sugar and stir.<br>\r\n9) let the sugar dissolve and after 3 to 4 mins, add the rice flour paste or corn starch paste.<br>\r\n10) keep on stirring after adding the paste, so that no lumps are formed.<br>\r\n11) the whole mixture has to be lump free, so keep on stirring.<br>\r\n12) after 4 to 5 mins, when the mixture has thickened, add the mawa/khoya, powdered almonds and pistachios along with cardamom powder.<br>\r\n13) stir very well and just simmer for a minute or two on a low flame. keep on stirring so that the khoya/evaporated milk is distributed evenly.<br>\r\n14) switch off the flame.<br>\r\n15) add the kewra (pandanus or screwpine) water or rose water and crushed saffron.<br>\r\n16) let the kulfi mixture cool.<br>\r\n17) then pour the kulfi mixture in kulfi moulds or in serving bowls or in a tray.<br>\r\n18) freeze the kulfi.<br>\r\n19) once the kulfi is well set, unmould the kulfi sliding a butter knife at the edges, remove on a plate.<br>\r\n20) slice the kulfi and serve immediately. <br>\r\n21) you can also serve kulfi directly in the serving bowls or glasses.<br>\r\n<br>\r\n'),
(12, 'Barfi', 5, 'barfi.jpg', '1) 50 gms unsweetened khoya/mava/evaporated milk</br>\r\n2) 5 tbsp sugar or add as required</br>\r\n3) 3 to 4 cardamoms, powdered in a small grinder or mortar-pestle, about 1/4 to 1/5tsp of cardamom powder, husks removed<br>\r\n4) 12 to 15 pistachios, finely chopped<br>\r\n5) 12 to 15 almonds or cashews, finely chopped<br>\r\n6) a pinch of saffron (optional)<br>\r\n7) 1 to 1.5 tsp milk (optional)<br>\r\n8) about 1/4 to 1/2 tsp ghee for greasing the pan or tray<br>\r\n', '1) first grate or crumble the unsweetened khoya.<br>\r\n2) in a small bowl dissolve a few saffron strands in 1 tsp of milk. this is an optional step.<br>\r\n3) grease a bit of ghee, on a butter paper lined on a tray or on a thali/tray.<br>\r\n4) add the grated khoya in a thick bottomed pan.<br>\r\n5) begin to cook on a low flame for 2 to 3 minutes stirring often.<br>\r\n6) switch off the flame and add sugar.<br>\r\n7) stir. then turn on the flame. the whole mixture''s consistency will become smooth and slightly thin, due to the sugar getting melted.<br>\r\n8) stir often and continue to cook on a low flame.<br>\r\n9) when the mixture becomes slightly thick and starts leaving the sides of the pan, as you see in the pic in step number 9, its time for the next step.<br>\r\n10) avoid cooking too much as then the barfi will have a chewy texture. <br>\r\n11) the time taken to get this texture right from the time, sugar is added is about 8 to 9 minutes on a low flame.<br>\r\n12) the time will vary a couple of minutes here and there, depending on the size, type, quality of the pan and intensity of the flame.<br>\r\n13) add chopped dry fruits (almonds, pistachios) or your choice of dry fruits. also add cardamom powder.<br>\r\n14) stir and cook for a minute. switch off the flame.<br>\r\n15) pour the entire barfi mixture in the greased pan or butter paper.<br>\r\n16) spread evenly keeping 1 inch thickness at the edges.<br>\r\n17) sprinkle the saffron scented milk on the barfi.<br>\r\n18) once the barfi cools down, slice into squares or diamond shapes.<br>\r\n19) serve khoya barfi immediately. you can also store them in an airtight box.<br>\r\n20) these barfi stay good for about 4 to 5 days in the refrigerator.<br>\r\n'),
(13, 'Mysore Pak', 5, 'mysorepak.jpg', '\r\n1) 100 gm chickpea<br>\r\n2) flour (besan)200 gm<br>\r\n3) sugar300 gm<br>\r\n4) ghee2 Tbsp<br>\r\n5) water1 Tbsp<br>\r\n6) milk 1 Tbsp\r\n7) refined oil <br>\r\n8) (odourless)1 pinch of turmeric 1 gm <br>\r\n9) (two pinches) of baking powder<br>\r\n       ', '1. Roast the flour (without any oil) on a low flame in a wok (kadai) for about 2-3 minutes ensuring that no lumps are formed.\r\n<br>\r\n2. Spread the hot flour on a plate. Keep aside.<br>\r\n3. Add water, milk and sugar to the wok and heat on a low flame. Also add a pinch of turmeric and oil (odourless) as your stir. (The oil lends a gloss to the sweet. The softer ''Mysurpa'' version uses extra milk)\r\n<br>\r\n4. Use a second wok (kadai) to melt the ghee on a medium flame.<br>\r\n5. Once the sugar syrup achieves a ''two thread consistency'' start adding the chickpea (besan) flour gradually and keep stirring as you do. Also add the baking powder at this point.<br>\r\n6. Add a ladle of ghee to the mixture. Wait for the remaining ghee (on the second wok) to reach boiling point before you turn it off.<br>\r\n7. Keep adding the boiling ghee to the first wok ensuring no lumps are formed. Turn off the flame once the mixture assumes a frothy and porous consistency.<br>\r\n8. Brush a plate with a little ghee. Ensure this plate is at least 5 cms high (so that you get the right height for the Mysore Pak)<br>\r\n9. Pour the mixture on to the plate. Add a little ghee on top of the mixture and also sprinkle some sugar on top.10. Cut the mixture in about five minutes when it''s still hot for the perfect shape and texture.<br>\r\n'),
(14, 'Sandesh', 5, 'sandesh.jpg', '1) 1 litre milk</br>\r\n2) 1 to 1.5 tbsp lemon juice or vinegar</br>\r\n3) 2 tbsp palm jaggery or substitute with just 2 tbsp sugar</br>\r\n4) 3 tbsp sugar or as required</br>\r\n5) 4-5 pistachios, almonds, sliced or 10-12 golden raisins</br>\r\n', '1) keep the milk to boil.</br>\r\n2) line a deep bowl or pan with a muslin or thin cotton napkin.</br>\r\n3) when the milk beguns boiling, lower the flame. add lemon juice and stir.</br>\r\n4) when all the milk curdles, switch off the fire.</br>\r\n5) pour the entire content in the lined muslin.</br>\r\n6) take the four corners of the muslin in your hands and join together.</br>\r\n7) the chenna or paneer would be in the muslin. so gather all the curdled paneer together in the muslin and squeeze the whey.</br>\r\n8) rinse the chenna with the muslin in running water very lightly. this is to remove the sourness of the lemon juice or vinegar from the paneer.</br>\r\n9) place a weight like a stone bowl or a stone pestle on the muslin for 25-30 mins.</br>\r\n10) take the paneer in a plate or a tray.</br>\r\n11) knead with the knuckles of your palms.</br>\r\n12) gather the whole mixture at intervals and then again continue to knead till the mixture becomes smooth and less granular.</br>\r\n13) add jaggery and sugar and knead for 2-3 minutes again.</br>\r\n14) the jaggery and sugar both will melt and release moisture in the mixture.</br>\r\n15) add this mixture to a thick bottomed non stick pan.</br>\r\n16) with continous stirring cook on a low flame for a total time of 9-10 minutes.</br>\r\n17) first the mixture will have a smooth and molten consistency.</br>\r\n18) slowly slowly the moisture would begin to dry up and the mixture would start coming together.</br>\r\n19) we do not want a dry sandesh mixture.</br>\r\n20) the paneer should have some moistness and must not have a dense rubbery texture.</br>\r\n21) remember the mixture should have some moistness and not be dry.</br>\r\n22) also no oil or fat should be released from the mixture.</br>\r\n23) let the mixture warm or cool and then knead the mixture again to get a smooth consistency.</br>\r\n24) shape into round flattened balls or a peda.</br>\r\n25) with a toothpick or fork you can even make designs on the sandesh.</br>\r\n26) press some pistachio or almond slices or raisins in the center.</br>\r\n27) serve the sandesh immediately or refrigerate and then serve them.</br>\r\n28) if not serving immediately then refrigerate the sandesh as they get spoiled if you keep them out at room temperature.</br>\r\n'),
(15, '\r\nKaju Katli', 5, 'kaju katli.jpg', '1) 1 cup cashews/kaju<br>\r\n2) 1/4 cup sugar or as required<br>\r\n3) 5 tbsp water<br>\r\n4) 1 tbsp ghee or coconut oil (optional)<br>\r\n5) 1 tsp chopped rose petals (optional) or rose water or 8-9 strands of saffron<br>\r\n', '1) powder the cashew in a coffee grinder or a dry grinder.<br>\r\n2) the cashews should be in powdered form and not become pasty or oily.<br>\r\n3) on a low flame heat sugar and water in a thick bottomed or non stick pan or kadai.<br>\r\n4) meanwhile grease a plate or a tray and keep aside or keep butter papers ready.<br>\r\n5) when all the sugar dissolved in the water, add the cashew powder.<br>\r\n6) there is no consistency in the sugar syrup required like one string or two string.<br>\r\n7) just let the sugar dissolve in the water and then proceed with the next step.<br>\r\n8) stir and keep on stirring the cashew mixture on a low flame.<br>\r\n'),
(16, '\r\nRabri', 5, 'rabdi.jpg', '1) 1.25 litres full fat whole milk, 5 cups.<br>\r\n2) 2.5 to 3 tbsp sugar or add as required.<br>\r\n3) 5 to 6 cardamoms, crushed or 1/2 tsp cardamom powder.<br>\r\n4) 12 to 15 saffron strands, crushed.<br>\r\n5) 1 tsp rose water or kewra water/pandanus extract.<br>\r\n6) 2 tbsp almonds and 2 tbsp pistachios, blanched & sliced<br>\r\n', '1) take 5 cups or 1.25 litres of full fat whole milk in a thick bottomed kadai or pan & begun to heat the milk on a low to medium flame, till the milk starts to froth or form a layer of cream/malai on top.<br>\r\n2) so when you will see the cream floating on top, then with a spatula, gently move the cream layer.<br>\r\n3) bring it towards the side of the pan and stick it to the pan.<br>\r\n4) keep on simmering the milk like this and collecting the cream layer on the sides.<br>\r\n5) meanwhile soak almonds and pistachios in hot water for 30 minutes. then remove their peels.<br>\r\n6) slice or chop them and keep aside. do keep a check on the simmering milk when soaking as well as slicing the almonds, pistachios.<br>\r\n7) this process of collecting the cream layer has to be done many times.<br>\r\n8) continuous simmering of the milk will bring the cream on top and you have to bring & stick it to the sides.<br> \r\n9) in between also stir the milk gently on occasions, so that the milk does not get burnt from the bottom.<br>\r\n10) if you do too much of stirring and if quickly, then you won''t get the layers of cream in the rabri.<br>\r\n11) you can also just thicken and scrape the milk solids from the sides like i have done for shahi tukda rabdi.<br>\r\n12) but in this case you won''t get the layers of cream or malai in the rabri.<br>\r\n13) but both versions taste good.<br>\r\n14) once the milk reduces to half, then add 2.5 to 3 tbsp sugar.<br>\r\n15) you can add sugar as per your taste.<br>\r\n16) then add a 12 to 15 strands of crushed saffron and 1/2 tsp cardamom powder. stir gently.<br>\r\n17) continue collecting the cream and bringing it to the sides of the pan.<br>\r\n18) also do stir the milk gently after you bring the cream towards the sides of the pan.<br>\r\n19) if you don''t stir the milk then there is a possibility of the milk getting browned or burnt from the bottom.<br>\r\n20) after adding saffron, the color will change gradually to a yellow color as the milk keeps on reducing.<br>\r\n21) when the milk gets reduced to 1/5 or 1/4 of its original quantity, then switch off the flame.<br>\r\n22) it took me about 1 hour 15 minutes on a low flame initially and medium flame towards the latter stage.<br>\r\n23) the cream layer will be collected on the sides.<br>\r\n24) scrape off the entire cream layer as well as dried milk solids and add to in the thickened milk.<br>\r\n25) stir gently. then add the sliced almonds & pistachios and 1 tsp rose water or kewra water. stir gently again.<br>\r\n26) garnish with some sliced almonds and serve rabri hot or warm or chilled.<br>\r\n'),
(17, 'Aam Ka Panna', 4, 'aampanna.jpg', '1. 3 medium size green raw mangoes<br>\r\n2. 1 cup Sugar <br>\r\n3. 1 tblsp roasted cumin powder<br>\r\n4. Black salt to taste <br>\r\n5. Salt to taste<br>\r\n6. 2 cup water<br>\r\n7. 1 tblsp Mint leaves (pudina patta)<br>\r\n8. Ice crushed<br>\r\n', '1. Place the mangoes along with water in a sauce-pan and bring to a boil. Simmer for 10 minutes.<br>\r\n2. Then remove from fire Alternately you can pressure cook the mangoes with water till soft.<br>\r\n3. Let them cool and then peel the mangoes and get the pulp with the help of a spoon.<br> \r\n4. Grind mango pulp along with water to a smooth paste.<br>\r\n5. In a pan take the pulpy mixture, add sugar and let it cook on flame till the sugar dissolves completely.<br> \r\n6. Stir continously lest you burn the mixture.<br>\r\n7. Remove from fire and add roasted cumin powder, black salt and salt.<br>\r\n8. Let this mixture cool down properly.<br>\r\n9. To make the drink : take a tall glass pour 1 -2 tblsp of the mango mixture and pour in chilled water till 3/4 th.<br> \r\n10. Now add finely chopped mint  and crushed ice.<br>\r\n11. Garnish with mint leaves and serve immediately.<br>\r\n'),
(18, 'Chass', 4, 'chass.jpg', '1. 5 cups curd/yogurt <br>\r\n2. half tsp roasted cumin powder/bhuna jeera powder or add as required<br>\r\n3. 1 cup water<br>\r\n4. 5 to 6 small ice cubes<br>\r\n6. black salt/kala namak as required<br>\r\n7. a few coriander leaves or mint leaves for garnish<br>\r\n', '1. take all the ingredients in a blender jar, except the coriander leaves.<br>\r\n2. just pulse the blender for some seconds till everything is blended well and the mixture becomes frothy.<br>\r\n3. pour chaas in glasses.<br>\r\n4. garnish with coriander leaves and serve chaas immediately.<br>\r\n5. you can also chill the butter milk in the refrigerator and serve later. but use it in the same day<br>\r\n'),
(19, 'Falooda', 4, 'falooda.jpg', '1. half cup falooda sev<br>\r\n2. 4 to 5 tbsp soaked sabja seeds/sweet basil seeds (soak about ½ tbsp sabja seeds in enough water)<br>\r\n3. 4 cups chilled whole milk<br>\r\n4. 4 scoops of vanilla ice cream<br>\r\n5. 5 to 6 tbsp rose syrup<br>\r\n6. 5 to 6 shelled pistachios, sliced or slivered<br>\r\n7. 5 to 6 cashews or almonds, sliced<br>\r\n8. 5 to 6 golden raisins<br>\r\n', '1. soak 1/2 tbsp of sabja seeds in water for about 30 to 40 mins. once they swell. drain and then keep aside.<br>\r\n2. prepare the falooda sev according to package instructions.<br>\r\n3. if cooking the sev, then once cooked, rinse the cooked falooda sev in water. drain and keep them aside. let them cool completely.<br>\r\n4. in 4 glasses each, add 1.5 to 2 tbsp rose syrup. depending upon your taste you can add less or more. 2 tbsp of rose syrup makes it more sweet.\r\nthen add 1 or 1.5 tbsp of sabja seeds<br>\r\n5. add 1 to 1.5 tbsp of the falooda sev.<br>\r\n6. in a slow stream, pour about ¾ to 1 cup milk.<br>\r\n7. then top with one scoop of vanilla ice cream.<br>\r\n8. garnish with a few raisins, sliced pistachios, almonds or cashews.<br>\r\n9. serve the falooda immediately.<br>\r\n'),
(20, '\r\nLassi', 4, 'lassi.jpeg', '1. 2 cups chilled fresh curd/dahi or yogurt <br>\r\n2. 5 to 2 cups chilled water or milk <br>\r\n3. 10 to 12 tbsp sugar or add as per taste <br>\r\n4. 1 tsp cardamom powder or 2 tsp rose water <br>\r\n5. a few strands of saffron/kesar (optional)<br>\r\n6. 6 to 8 ice cubes (optional)<br>\r\n7. 1 to 2 tbsp chopped or sliced dry fruits (optional)<br>\r\n', '1. in a mortar, take 8 to 10 cardamom pods and crush them. remove the husk and crush the seeds. <br>\r\n2. crush to a fine powder.<br>\r\n3. in a bowl or pan, take 2 cups fresh chilled yogurt. i used homemade curd.<br>\r\n4. with a madani or blender or wired whisk just mix the curd till it become smooth.<br>\r\n5. the curd should be smooth before you add other ingredients to it.<br>\r\n6. add 10 to 12 tbsp sugar or as required.<br>\r\n7. then add 2 cups chilled water. you can also add 2 cups chilled milk, instead of water. the consistency of this lassi is neither thin nor thick. <br>\r\n8. if you want a thick lassi, then add 1 to 1.5 cups water. <br>\r\n9. now churn the madani in the lassi mixture. <br>\r\n10. keep on churning till the sugar dissolves and you see a nice frothy layer on top. you can also use an immersion blender for the same. <br>\r\n11. another way is to add everything in a blender jar and blend till smooth. <br>\r\n12. now add 1 tsp of the crushed cardamom powder and a few saffron strands. as a substitute for cardamom powder, you can also add 2 tsp of rose water. <br>\r\n13. you can also skip all the flavoring ingredients, if you don''t have any.<br>\r\n14. just mix with the madani again. add ice cubes and mix again.<br>\r\n15. pour lassi in tall glasses and serve. if you want, you can also top the lassi with 1 to 2 tbsp of malai (cream which collect on top of milk) or 1 to 2 tbsp of unsalted white butter/makhan.<br>\r\n16. garnish lassi with a pinch or two of cardamom powder, 2 to 3 saffron strands or chopped dry fruits. serve sweet punjabi lassi immediately.<br>\r\n'),
(21, 'Masala chai', 4, 'masalachai.jpg', '1. 1 tsp. or 5 grams Green cardamoms skinned (elaichi)<br>\r\n2. half tsp or 2 grams cloves / lavang<br>\r\n3. 5 to 3 grams cinnamon (dalchini)<br>\r\n4. one fourth tsp. or 1.5 grams fennel seeds (saunf)<br>\r\n5. 1/4 to 1/2 tsp pepper corn or 1/2 tsp. powder<br>\r\n6. 1/2 tsp. nutmeg grated or 1/3 of large nutmeg<br>\r\n7. 2 petals of star flower / star anise (chakri phool)<br>\r\n8. 3/4cup milk (180 ml)<br>\r\n9. 1 cup water (240 ml)<br>\r\n10. half tsp. masalapowder (you can increase slightly for stronger tea)<br>\r\n11. tsp. tea powder (adjust to suit your taste)<br>\r\n12. 1 tsp. freshly chopped or crushed ginger<br>\r\n13. Sweetener as needed<br>\r\n', '1. Add all the spices to blender jar and powder finely.<br>\r\n2. Store it in an airtight glass jar.<br>\r\n3. How to make masala tea using the spice powder.<br>\r\n4. Bring one cup of water to a boil.<br>\r\n5. Add crushed ginger, spice powder and tea powder. Boil for about 2 to 3 minutes or till the flavors are infused well.<br>\r\n6. Add milk and simmer for 2 to 3 minutes.<br>\r\n7. Filter it to the serving cups.<br>\r\n8. Serve hot or warm.<br>\r\n\r\n'),
(22, 'Jal Jeera', 4, 'jaljeera.jpg', '1. 1 tbsp seedless tamarind - for a pronounced more sourness, you can add ½ tbsp of more tamarind.<br>\r\n2. 3/4 cup mint leaves/pudina patta<br>\r\n3. 1 or 1.5 tsp cumin seeds/jeera<br>\r\n4. 1 tsp fennel seeds/saunf<br>\r\n5. 1/2 tsp black pepper<br>\r\n6. 1/2 or 1 tsp amchur/dry mango powder<br>\r\n7. seeds removed from 1 black cardamom (optional)<br>\r\n8. a pinch of asafoetida/hing (optional)<br>\r\n9. 1 tbsp boondi<br>\r\n10. 1/2 or 1 tsp chaat masala powder (optional)<br>\r\n11. black salt or rock salt as required<br>\r\n', '1. rinse the mint leaves.<br>\r\n2. also rinse the tamarind ball.<br>\r\n3. first blend all the ingredients except boondi and chaat masala in 1/2 or 3/4 cup water till smooth.<br>\r\nthen strain through a strainer<br>\r\n4. add 3-4 cups of chilled water to the strained mixture or as required<br>\r\n5. keep in the fridge or serve chilled jaljeera.<br>\r\n6. add boondi and a pinch of chaat masala to jaljeera while serving.<br>\r\n'),
(23, 'Nimbu Pani', 4, 'nimbupani.jpg', '1. 1 medium size lemon<br>\r\n2. 2 glasses of water<br>\r\n3. 1 tsp cumin powder<br>\r\n4. rock salt or black salt as required<br>\r\n6. sugar as required<br>\r\n7. 4-5 mint leaves for garnishing - optional<br>\r\n8. a few ice cubes<br>\r\n', '1. cut the lemon in to two.<br>\r\n2. take 2 glasses of a water in a bowl<br>\r\n3. with a lemon juice squeezer, squeeze the juice directly into the water.<br>\r\n4. add black salt, sugar, jeera powder.<br>\r\n5. stir till the sugar dissolves.<br>\r\n6. pour the shikanji in glasses. add ice cubes. garnish with mint and serve shikanji immediately.<br>\r\n7. you can also make the shikanji and chill in the fridge and then serve.<br>\r\n'),
(24, '\r\nHaldi doodh', 4, 'haldidoodh.jpg', '1. an inch piece of turmeric root, grated or 1 teaspoon of turmeric powder<br>\r\n2. 220 ml of milk<br>\r\n3. honey/ sugar to taste<br>\r\n4. optionally freshly pounded black pepper<br>\r\n', '1. To begin making the Turmeric Milk (Haldi Doodh), bring the grated turmeric and milk to boil for a couple of minutes. <br>\r\n2. Once it boils, turn off the heat and allow the turmeric milk mixture to rest covered for a couple of more minutes.<br>  \r\n3. This will bring out the essential medicines and color from the turmeric. <br>\r\n4. After a couple of minutes of resting, strain the milk from the turmeric into a glass, stir in sugar / honey and black pepper and serve the Turmeric Milk while still hot.<br>\r\n'),
(25, 'Baati ', 3, 'baati.jpg', '1) Split green gram skinless 1/4 cup<br>\r\n2) Split black gram skinless 1 cup<br>\r\n3) Split Bengal gram (chana dal) 1/4 cup<br>\r\n4) Red chilli powder 1 teaspoon<br>\r\n5) Ginger,chopped 2 inch piece<br>\r\n6) Turmeric powder 1/2 teaspoon<br>\r\n7) Cumin seeds 1 teaspoon<br>\r\n8) As a foetida a pinch<br>\r\n9) Whole dry red chillies broken stemmed 2<br>\r\n10) Cloves 3<br>\r\n11) Green cardamoms 2<br>\r\n12) Cinnamon 1 inch stick<br>\r\n13) Bay leaves 2<br>\r\n14) Curry leaves 5-6<br>\r\n15) Tomatoes 2 medium<br>\r\n16) Green chillies chopped 3<br>\r\n17) Salt to taste<br>\r\n18) Oil 4 tablespoons<br>\r\n19) Fresh coriander leaves chopped 1/4 cup<br>\r\n20) Lemon 1 medium<br>\r\n21) Whole wheat flour (atta) 2 cups<br>\r\n22) Carom seeds (ajwain) 1 teaspoon<br>\r\n23) Baking powder 1/4 teaspoon<br>\r\n24) Pure ghee 1 cup + for soaking and serving<br>\r\n', 'Step 1<br>\r\n\r\nSoak moong dal, urad dal and chana dal in about three cups of water for an hour. Boil the dals with turmeric and salt till done and mash them properly with the back of a round ladle. Heat oil in a pan. Add cumin seeds, asafoetida, dry red chillies, bay leaves, cloves, cinnamon, cardamoms, curry leaves, ginger, green chillies, tomatoes and red chilli powder. Sauté till the oil surfaces.<br>\r\n\r\nStep 2<br>\r\n\r\nAdd the cooked dals to this and blend properly. Finish off with juice of lemon and chopped coriander leaves.<br>\r\n\r\nStep 3<br>\r\n\r\nto make batis, take atta in a bowl. Add salt, baking powder and half a cup of pure ghee. Mix well. Add sufficient water and knead into a stiff dough. Preheat oven to 180°C.<br>\r\n\r\nStep 4<br>\r\n\r\nTake lemon sized portions. Press firmly and roll into round balls. Grease a baking tray. Place the baatis on it. Press them slightly. Place the tray in the preheated oven and bake at 180°C till done. It may take fifteen minutes to half an hour.<br>\r\n\r\nStep 5<br>\r\n\r\nWhen done, serve it hot with a bowl full of pure ghee to soak baatis and dal.<br>\r\n\r\n'),
(26, 'Bhakri', 3, 'bhakri.jpg', '1) 2 to 21/2 cups bajra flour/millet flour<br>\r\n2) 1 tsp oil or ghee<br>\r\n3) water as required<br>\r\n4) salt as required<br>\r\n5) some bajra flour or whole wheat flour for dusting<br>\r\n6) sunflower oil or ghee for applying on the rotis or for frying them<br>\r\n', '1) heat or warm the water. add salt and oil. stir.<br>\r\n2) add the bajra flour. stir with a spoon. knead into a smooth dough.<br>\r\n3) if the dough becomes sticky, then add more flour. if the dough is dry, then add some water.<br>\r\n4) meanwhile heat a tava or flat fry pan.<br>\r\n5) make medium sized balls. dust with flour and use a ziplock bag for rolling.<br>\r\n6) remove gently from the ziplock bag and place on the hot tava.<br>\r\n7) cook till both sides have brown spots and done.<br>\r\n8) apply oil or ghee on one side.<br>\r\n9) you can also fry the bajra rotis like parathas with oil or ghee directly in the tava/frying pan.<br>\r\n10) serve bajra roti hot or warm with a vegetable side dish or curry.<br>\r\n'),
(27, 'Bhature', 3, 'bhature.jpg', '1) 2.5 cups atta or whole wheat flour<br>\r\n2) 1 tsp salt or as required<br>\r\n3) 1 tbsp oil or ghee or butter<br>\r\n4) 1/2 or 1/3 cup warm water<br>\r\n5) vegetable oil for deep frying<br>\r\nfor overnight fermentation:<br>\r\n6) 3/4 cup (150 ml) plain curd/yoghurt or cashew curd<br>\r\n7) 1/2 tbsp sugar or brown sugar<br>\r\n8) 1/2 tsp baking powder<br>\r\n9) 3/4 cup all purpose flour/maida<br>\r\n10) 1/4 cup water (optional)<br>\r\n', '1) You will have to start the night before.<br>\r\n2) In a bowl take the yoghurt, sugar, baking powder and all purpose flour.<br>\r\n3) Mix well all the above 4 ingredients mentioned for overnight fermentation.<br>\r\n4) If the yogurt has whey in it, then don''t need to add the 1/4 cup water mentioned above.<br>\r\n5) If the yogurt is thick, then to thin the batter, add 1/4 cup water.<br>\r\n6) Cover the bowl with a cloth and set it aside in a warm place overnight or for 8 hours to allow natural fermentation to take place.<br>\r\n7) The next day you will see tiny bubbles on the surface of the mixture. The mixture is ready for the next step when tiny bubbles appear on the surface.<br>\r\n8) In another bowl, mix together the wheat flour with salt and rub the ghee or butter into it with your fingertips. Into this bowl, add the fermenting mixture and the warm water. Form a dough with these two mixtures.<br>\r\n9) Knead the dough for 5 to 10 minutes or until it is silky smooth. Add a little flour if it is too wet. Gather the dough into a compact ball and cover it with a damp cloth. Again set it aside in a warm place for 2 hrs.<br>\r\n10) This is how the dough appears after 2 hours.<br>\r\n11) Knead the dough again.<br>\r\n12) Form it in to 15 balls and roll them into 5-6 inch discs. Heat oil or ghee and deep fry the bhaturas in the same way as you would fry pooris. Serve the bhaturas hot with chole and wedges of lemon and sliced onions.<br>\r\n'),
(28, 'Chapatis', 3, 'chapati.jpg', '1) 3 cups whole wheat flour/atta<br>\r\n2) 1 to 1.25 cups water or more if needed<br>\r\n3) 1/2 to 3/4 tsp salt (optional)<br>\r\n4) 1 to 2 tsp oil or ghee (optional)<br>\r\n', '1) take whole wheat flour/atta in a bowl. seive the whole wheat flour with salt. add a bit of water and ghee and start mixing.<br>\r\n2) adding some water to the dough in parts, begin to knead the dough.<br>\r\n3) continue to knead the dough. keep on adding water as required.<br>\r\n4) knead the dough till it becomes pliable and soft. the final dough consistency should not be very soft or hard.<br>\r\n5) now make small to medium balls of the dough. roll the balls in the palms of your hands.<br>\r\n6) flatten the ball. sprinkle some whole wheat flour to the dough ball. alternatively, you can also dust the rolling board with flour.<br>\r\n7) turn on the gas stove and put the tawa to make it hot.<br>\r\n8) while tawa is getting hot, start rolling the dough ball into a flat round circle.<br>\r\n9) once the tawa is sufficiently hot then put the roti on a hot tawa/griddle.<br>\r\n10) first cook one side. it should be less than half cooked or about one-fourth cooked.<br>\r\n11) turn and cook the other side. this should be a little bit more cooked than the first side. brown spots should be visible.<br>\r\n12) now hold the roti with a tong and keep the first side which was cooked, directly on fire. the roti will start to puff.<br>\r\n13) turn and keep the other side on fire. the roti will puff more. avoid burning the rotis and also don’t overdo it as roti will not be soft and will become crisp and hard like papads.<br>\r\n14) remove and apply ghee on the rotis. applying ghee or oil keep them soft for a long time. rotis made with this method is ideally served hot.<br>\r\n15) if you cannot serve them hot, then you can keep them in a container that keeps food warm like a casserole or in a roti basket. you can also wrap them up in a kitchen towel or napkin.<br>\r\n16) serve the soft rotis with dal or a veggie dish.<br>\r\n'),
(29, 'Kachori', 3, 'kachori.jpg', ' for the pastry:<br>\r\n1) 1 cup all purpose flour/maida (you can also use whole wheat flour or both the flours in 50:50 amount)<br>\r\n2) 1 tbsp oil or ghee ((i used sunflower oil)<br>\r\n3) 1/4 cup warm water<br>\r\n4) 1/4 tsp baking powder<br>\r\n5) 1/4 tsp salt<br>\r\nfor the stuffing:<br>\r\n1) 1 cup peas, fresh or frozen<br>\r\n2) 1/4 tsp red chili powder/lal mirch<br>\r\n3) 1/4 tsp turmeric powder/haldi<br>\r\n4) 1/2 tsp coriander powder/dhania powder<br>\r\n5) 1/2 tsp fennel powder/saunf powder<br>\r\n6) 1/2 tsp chaat masala<br>\r\n7) 1/2 tsp amchur powder/dry mango powder<br>\r\n8) 1/2 tsp green chili-ginger paste or crushed or minced (use about 1/4 inch of ginger and 1/2 or 1 green chili and crush in a mortar & pestle)<br>\r\n9) 1/4 tsp cumin/jeera<br>\r\n10) 1 tbsp besan or gram flour<br>\r\n11) 2 tsp oil or ghee<br>\r\n12) salt as required<br>\r\nfor frying:<br>\r\n1) 2 to 3 cups oil<br>\r\n', '1) sift the flour, salt and baking powder. add oil and form a bread crumb like mixture.<br>\r\n2) add water and form a tight dough. cover with a damp cloth and keep aside.<br>\r\npreparing the pea stuffing:<br>\r\n1) boil or steam the peas. mash them coarsely or semi-coarsely.<br>\r\n2) heat oil and fry the cumin. then add the crushed ginger and green chili.<br>\r\n3) fry for a minute. now add the dry spice powders and salt.<br>\r\n4) stir and add the gram flour. saute for 2-3 minutes.<br>\r\n5) check the seasoning and add some more of the spice powders or salt, if required.<br>\r\npreparing the kachoris:<br>\r\n1) make equal sized 5-6 balls from the dough. roll into 3-4 inch round on a dusted board.<br>\r\n2) add some of the stuffing in the center. brush some water on the edges.<br>\r\n3) bring together all the edges and pinch them. press the edges downwards below.<br>\r\n4) roll into a 4-5 inches kachori. prepare all matar kachoris like these. keep the kachoris covered with a wet cloth.<br>\r\n5) now heat oil. at medium flame, fry the kachoris till they become golden, flaky and crisp.<br>\r\n6) serve matar kachori hot with some coriander chutney or tamarind chutney.<br>\r\n'),
(30, 'Khakhra', 3, 'khakra.jpg', '1) Whole wheat flour (atta) 1 cup<br>\r\n2) Refined flour (maida) 1 cup<br>\r\n3) Garam masala powder 1 teaspoon<br>\r\n4) Oil 2 tablespoons<br>\r\n5) Water or warm milk as required<br>\r\n6) Ghee 4 teaspoons<br>\r\n7) Salt to taste<br>\r\n', 'Step 1<br>\r\n\r\nSieve together wheat flour, refined flour, salt and garam masala powder into a bowl. Add oil, enough water or milk and knead to make a soft dough.<br>\r\n\r\nStep 2<br>\r\n\r\nDivide the dough into eight balls and roll out each ball into very thin chapatis. Heat a thick tawa, put the chapatti on it and roast on slow heat.<br>\r\n\r\nStep 3<br>\r\n\r\nApply a little ghee on both sides. Turn and hold it down with a wooden press. When it is crisp and light brown in colour on both the sides, it is done. Remove, allow it to cool and store in an airtight container carefully as it is very crisp and may break.<br>\r\n'),
(31, 'Parantha', 3, 'parantha.jpg', '1) 2 cups whole wheat flour/atta<br>\r\n2) 1 to 2 tsp oil or ghee<br>\r\n3) 1/2 tsp salt or add as required<br>\r\n4) water as required for kneading the dough<br>\r\n5) oil or ghee for roasting, as required<br>\r\n', '1) in a bowl take whole wheat flour. add salt, oil and water.<br>\r\n2) mix and then knead into a smooth soft dough. add more water if required while kneading. cover and keep the dough aside for 30 minutes.<br>\r\n triangular folded plain paratha method:<br>\r\n3) pinch a medium sized ball from the dough. flatten and dust with some flour.<br>\r\n4) with a rolling pin, roll into a circle of about 4 inches diameter.<br>\r\n5) spread some ghee on the dough circle. fold in a half.<br>\r\n6) now spread some ghee on this half folded dough.<br>\r\n7) fold sideways and this time you will get a folded triangle.<br>\r\n8) dust some flour on the folded triangle. now begin to roll the folded triangle.<br>\r\n9) add some flour if required and roll into a circle of about 6 to 7 inches diameter.<br>\r\n    square folded paratha method:<br>\r\n10) roll a medium sized ball on a lightly dusted board to a circle of about 4 to 5 inches in diameter.<br>\r\n11) spread some ghee on the rolled dough.<br>\r\n12) bring one side of rolled dough towards the center and press lightly.<br>\r\n13) now spread again some ghee on the folded part.<br>\r\n14) fold the opposite side of the rolled dough on top of the folded part. press lightly.<br>\r\n15) again spread some ghee on this second folded part.<br>\r\n16) fold the right side and bring towards the center. spread some ghee on this fold too.<br>\r\n17) lastly fold the left side on top of the right fold.<br>\r\n18) sprinkle some flour on the folded paratha.<br>\r\n19) begin to roll. add some more flour if required while rolling. roll into a square paratha.<br>\r\n20) heat tava and place the paratha on the tava. the tava should be medium hot.<br>\r\n21) you will soon see the paratha puffing up from the base at some places.<br>\r\n22) flip the paratha when the base is ¼ cooked. spread some ghee.<br>\r\n23) flip again when the second side is about ½ cooked. you will see brown spots now.<br>\r\n24) spread some ghee on this side now.<br>\r\n25) flip again a couple of times till you see more brown spots and the paratha is cooked evenly. make all parathas this way. either serve them hot or stack them in a roti basket.<br>\r\n26) serve these plain parathas with any indian dal or vegetable curry.<br>\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `userID` int(2) NOT NULL,
  `username` varchar(30) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`userID`, `username`, `password`) VALUES
(1, 'admin', '8e3b3d0d5e13af02ff1c738501299c6a2f5933ed');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`categoryID`);

--
-- Indexes for table `stock`
--
ALTER TABLE `stock`
  ADD PRIMARY KEY (`recipeID`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`userID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `categoryID` int(2) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=6;
--
-- AUTO_INCREMENT for table `stock`
--
ALTER TABLE `stock`
  MODIFY `recipeID` int(2) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=102;
--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `userID` int(2) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
